name: Deploy Django on Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          # 1. Navegar al directorio del proyecto
          cd C:\deployments\mierp\env\mierp-TI1A
          
          # 2. Actualizar el repositorio
          git pull origin main
          
          # 3. Activar el entorno virtual y actualizar dependencias
          call C:\deployments\mierp\env\Scripts\activate
          cd C:\deployments\mierp\env\mierp-TI1A\mierpti1a
          pip install -r requirements.txt

          # 4. Migrar la base de datos y recopilar estáticos
          python manage.py migrate
          python manage.py collectstatic --noinput

          # 5. Detener el servidor Waitress si ya está corriendo
          taskkill /f /im waitress-serve.exe || echo "Waitress not running"

          # 6. Iniciar Waitress
          start /b waitress-serve --host=0.0.0.0 --port=8000 --threads=8 mierpti1a.wsgi:application

          # 7. Configurar Nginx
          echo "Configurando Nginx"
          
          # 7.1 Copiar archivo de configuración de Nginx desde el repositorio al servidor
          copy /y C:\deployments\mierp\env\mierp-TI1A\deploy\nginx.conf C:\nginx-1.27.3\conf\nginx.conf

          # 7.2 Recargar Nginx para aplicar cambios
          C:\nginx-1.27.3\nginx.exe -s reload || echo "NGINX reload failed"